### ISSUE TITLE
Error with Request.Body handling, receiving GOAWAY frames..

### ISSUE THREAD

**Issue by ghost** [ethanpailes/golang-org-x-net#1]
websocket.Dial https://buxflip.com/ws: http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error

not exactly sure the reason for this, but would like to understand why it is happening and if you could fix it.

**Comment by ethanpailes** [comment]
I just made this fork to have a place to post example patches for the go standard library. This isn't a place for websocket support. I would try sending your question to the go-nuts mailing list or posting on stackoverflow.

**Comment by ghost** [comment]
damn. i really wish they impleted websockets for http2 already

**Comment by ethanpailes** [comment]
I've written the patches, and there was just recently some movement from the maintainers on it. I'm just waiting for a confirmation that I should go ahead and bake the first of the patches into its final form. If you want, you could try bumping this thread: https://github.com/golang/go/issues/53208
